# GitLab CI/CD Pipeline para VitePress
# Deploy automático para GitLab Pages

stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  VITEPRESS_DIST_DIR: "docs/.vitepress/dist"

# Cache para node_modules
cache:
  paths:
    - node_modules/
    - .npm/

# Job de Build
build:
  stage: build
  image: node:18-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build
  artifacts:
    paths:
      - $VITEPRESS_DIST_DIR
    expire_in: 1 hour
  only:
    - main
    - master

# Job de Deploy para GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    - rsync -av --delete $VITEPRESS_DIST_DIR/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - build
  only:
    - main
    - master

# Job opcional para deploy em branches de desenvolvimento
deploy_preview:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    - rsync -av --delete $VITEPRESS_DIST_DIR/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  dependencies:
    - build
  except:
    - main
    - master
  when: manual
