# CI/CD para VitePress no GitLab Pages self-hosted (pg.portalidea.top)
# Inclui suporte a domínio customizado e cache otimizado

stages:
  - build
  - deploy
  - cleanup

variables:
  NODE_VERSION: "18"
  VITEPRESS_DIST_DIR: "docs/.vitepress/dist"

# Cache global para acelerar builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

# Build stage
build:
  stage: build
  image: node:${NODE_VERSION}-alpine
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "Compilando site com VitePress..."
    - npm run build
    - echo "Build concluído com sucesso"
  artifacts:
    paths:
      - $VITEPRESS_DIST_DIR
    expire_in: 1 hour
  only:
    - main
    - master
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# Deploy padrão para GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    - echo "Deploy para GitLab Pages..."
    - mkdir -p public
    - rsync -av --delete $VITEPRESS_DIST_DIR/ public/
    - echo "Deploy concluído"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - build
  only:
    - main
    - master
  environment:
    name: production
    url: https://$CI_PROJECT_PATH_SLUG.pg.portalidea.top

# Deploy manual para domínio customizado (opcional)
deploy_custom_domain:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    - echo "Deploy para domínio customizado: $CUSTOM_DOMAIN"
    - mkdir -p public
    - rsync -av --delete $VITEPRESS_DIST_DIR/ public/
    - echo "$CUSTOM_DOMAIN" > public/CNAME
    - echo "Deploy custom domain concluído"
  artifacts:
    paths:
      - public
    expire_in: 1 week
  dependencies:
    - build
  only:
    - main
    - master
  when: manual
  environment:
    name: custom-domain
    url: https://$CUSTOM_DOMAIN

# Pré-visualização de branches (manual)
deploy_preview:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync
  script:
    - echo "Deploy de pré-visualização para branch $CI_COMMIT_REF_NAME"
    - mkdir -p public
    - rsync -av --delete $VITEPRESS_DIST_DIR/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  dependencies:
    - build
  except:
    - main
    - master
  when: manual
  environment:
    name: preview/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_PATH_SLUG.pg.portalidea.top/-/jobs/$CI_JOB_ID/artifacts/public

# Limpeza pós-pipeline (opcional)
cleanup:
  stage: cleanup
  image: alpine:latest
  script:
    - echo "Limpando cache e dependências..."
    - rm -rf node_modules/ .npm/
  when: always
  only:
    - main
    - master